### ISSUE TITLE
Cannot be uploaded from the plugin gallery

### ISSUE THREAD

**Issue by Vitaliy-1** [NateWr/defaultManuscript#15]
I believe that it because the latest release is in the `zip` format, right?

**Comment by NateWr** [comment]
Hmm, yes, maybe that is an issue.

**Comment by ctgraham** [comment]
Can confirm.  The code only expects the `tar` command:
https://github.com/pkp/pkp-lib/blob/164758310831fcfac6931c1e6fc1b51f66ff0793/classes/plugins/PluginHelper.inc.php#L61-L67
The results of the system call are not checked to report a useful error message.

**Comment by NateWr** [comment]
I'll fix this with the next release, if that's soon enough! :)

**Comment by kaitlinnewson** [comment]
This also prevents the theme from being upgraded in 3.1.2, and we've had to manually install the theme in `plugins/themes`. Hopefully this can be resolved soon!

**Comment by ihdl** [comment]
We've tried to instal the Manuscript theme plugin via the plugin gallery on our OJS 3.1.1 and 3.1.2 test instances without success. 

`PHP Fatal error:  Uncaught Error: Call to a member function getProductType() on string in /data/ojs/xxx/lib/pkp/classes/plugins/PluginHelper.inc.php:113  `

Seems to be the same problem as described here. There has not been a release since, has there?

**Comment by ihdl** [comment]
Hi again, I just wanted to stress that we're very interested in this bug being fixed soon as well. We were planing to use the manuscript theme for a make-over of our journal's design. Due to limited resources, our (library) OSJ hosting provider is not able to install the theme if it's not available via the plugin gallery. So we cannot continue as planned at this point until the bug is fixed.

**Comment by ctgraham** [comment]
@NateWr , can you re-release?  Would be a good time to merge the PRs for the italian and arabic locales.

**Comment by NateWr** [comment]
OK will do this week or early next. Sorry for the mishap here. I may not get the locales in for the 3.1.x release since a 3.2 one will be coming so soon.

**Comment by NateWr** [comment]
I've just added a `.tar.gz` to the 1.0.2 release packages and updated the `plugins.xml` file to specify that one. I did a test install and it worked for me but let me know if there's any further problems.
